import generatedProvidersData from './generated-providers.json';

export interface AIConfig {
  preferredProvider: string;
  preferredModel: string;
  customProviders: CustomProvider[];
}

export interface CustomProvider {
  id: string;
  name: string;
  baseUrl: string;
  models: { id: string; name: string }[];
}

export interface ModelConfig {
  id: string;
  name: string;
}

export interface ProviderConfig {
  id: string;
  name: string;
  baseUrl: string;
  models: ModelConfig[];
}

/** Opaque JSON Schema object — forwarded into provider request bodies and/or
 * embedded in the prompt text; see callAIStructured. */
export type JsonSchema = Record<string, unknown>;

/** Compiled-in last resort when both the remote and local models-config.json
 * fetches fail (e.g. fully offline). Generated by scripts/generate-providers.mjs
 * from the same source as models-config.json, so this can no longer drift
 * from the runtime-fetched list the way the old hand-written array did. */
const FALLBACK_PROVIDERS: ProviderConfig[] = (
  generatedProvidersData.providers as (ProviderConfig & { essential?: boolean })[]
)
  .filter(p => p.essential)
  .map(({ id, name, baseUrl, models }) => ({ id, name, baseUrl, models }));


export async function getApiKey(provider: string): Promise<string | null> {
  if (window.desktopAPI?.getApiKey) {
    try {
      return (await window.desktopAPI.getApiKey(provider)) || null;
    } catch (e) {
      console.error('Failed to get key from tauri keyring:', e);
    }
  }
  return localStorage.getItem(`sutrata_api_key_${provider}`);
}

export async function setApiKey(provider: string, key: string): Promise<void> {
  if (window.desktopAPI?.setApiKey) {
    try {
      await window.desktopAPI.setApiKey(provider, key);
      return;
    } catch (e) {
      console.error('Failed to set key in tauri keyring:', e);
    }
  }
  localStorage.setItem(`sutrata_api_key_${provider}`, key);
}

export async function deleteApiKey(provider: string): Promise<void> {
  if (window.desktopAPI?.deleteApiKey) {
    try {
      await window.desktopAPI.deleteApiKey(provider);
      return;
    } catch (e) {
      console.error('Failed to delete key from tauri keyring:', e);
    }
  }
  localStorage.removeItem(`sutrata_api_key_${provider}`);
}

export function getAIConfig(): AIConfig {
  const stored = localStorage.getItem('sutrata_ai_config');
  if (stored) {
    try {
      return JSON.parse(stored);
    } catch {
      // ignore
    }
  }
  return {
    // No model id is hardcoded here — callAI/callAIStructured already fall
    // back to the chosen provider's first available model when
    // preferredModel doesn't match one of its models.
    preferredProvider: 'anthropic',
    preferredModel: '',
    customProviders: [],
  };
}

export function saveAIConfig(config: AIConfig): void {
  localStorage.setItem('sutrata_ai_config', JSON.stringify(config));
}

let cachedProviders: ProviderConfig[] | null = null;

export async function fetchProviders(config?: AIConfig): Promise<ProviderConfig[]> {
  if (cachedProviders) {
    return mergeCustomProviders(cachedProviders, config?.customProviders);
  }

  const isProd = (import.meta as any).env?.PROD;
  const githubUrl = 'https://raw.githubusercontent.com/sivarajd/sutrata/main/packages/app/public/models-config.json';
  
  let providers: ProviderConfig[] = [];
  
  if (isProd) {
    try {
      const res = await fetch(githubUrl);
      if (res.ok) {
        const data = await res.json();
        providers = data.providers || [];
      }
    } catch (e) {
      console.warn('Failed to fetch models config from github raw URL, falling back to local:', e);
    }
  }

  if (providers.length === 0) {
    try {
      const res = await fetch('/models-config.json');
      if (res.ok) {
        const data = await res.json();
        providers = data.providers || [];
      }
    } catch (e) {
      console.error('Failed to fetch local models-config.json:', e);
    }
  }

  if (providers.length === 0) {
    // Both the remote and local fetches failed (or returned nothing) — use
    // the compiled-in snapshot generated at build time. See FALLBACK_PROVIDERS.
    providers = FALLBACK_PROVIDERS;
  }

  cachedProviders = providers;
  return mergeCustomProviders(providers, config?.customProviders);
}

function mergeCustomProviders(
  base: ProviderConfig[],
  custom: CustomProvider[] | undefined
): ProviderConfig[] {
  if (!custom || custom.length === 0) return base;
  const list = [...base];
  for (const c of custom) {
    const index = list.findIndex(p => p.id === c.id);
    if (index >= 0) {
      const existing = list[index]!;
      list[index] = {
        ...existing,
        name: c.name,
        baseUrl: c.baseUrl,
        models: c.models,
      };
    } else {
      list.push({
        id: c.id,
        name: c.name,
        baseUrl: c.baseUrl,
        models: c.models,
      });
    }
  }
  return list;
}

interface ApiResponse {
  status: number;
  data: any;
}

async function requestHttp(
  url: string,
  method: string,
  headers: Record<string, string>,
  body: any
): Promise<ApiResponse> {
  if (window.desktopAPI?.callProviderApi) {
    try {
      const res = await window.desktopAPI.callProviderApi(url, method, headers, body);
      return res;
    } catch (e) {
      throw new Error(`Desktop API Error: ${e}`);
    }
  } else {
    try {
      const res = await fetch(url, {
        method,
        headers,
        body: body ? JSON.stringify(body) : undefined,
      });
      let data;
      const text = await res.text();
      try {
        data = JSON.parse(text);
      } catch {
        data = text;
      }
      return {
        status: res.status,
        data,
      };
    } catch (e) {
      throw new Error(`Web Fetch Error: ${e}`);
    }
  }
}

const STRUCTURED_TOOL_NAME = 'emit_result';

/**
 * Anthropic has no OpenAI-compatible endpoint, so it's the only provider
 * that still needs a bespoke request/response shape here — everyone else
 * (including Gemini, via its official /v1beta/openai compat base URL) goes
 * through the generic OpenAI-compatible branch below.
 */
async function invokeProvider(
  provider: ProviderConfig,
  model: string,
  key: string,
  prompt: string,
  systemPrompt: string,
  responseSchema?: JsonSchema
): Promise<string> {
  let url = '';
  let headers: Record<string, string> = {};
  let body: any = null;
  const method = 'POST';

  if (provider.id === 'anthropic') {
    url = `${provider.baseUrl}/messages`;
    headers = {
      'x-api-key': key,
      'anthropic-version': '2023-06-01',
      'content-type': 'application/json',
    };
    body = {
      model,
      max_tokens: 2000,
      system: systemPrompt,
      messages: [
        { role: 'user', content: prompt }
      ],
      temperature: 0.1,
    };
    if (responseSchema) {
      // Force a schema-valid tool call instead of parsing free text —
      // guarantees the fields we asked for, in the shape we asked for.
      body.tools = [{
        name: STRUCTURED_TOOL_NAME,
        description: 'Return the structured result for this request.',
        input_schema: responseSchema,
        strict: true,
      }];
      body.tool_choice = { type: 'tool', name: STRUCTURED_TOOL_NAME };
    }
  } else {
    url = `${provider.baseUrl}/chat/completions`;
    headers = {
      'Authorization': `Bearer ${key}`,
      'Content-Type': 'application/json',
    };
    const effectiveSystemPrompt = responseSchema
      ? `${systemPrompt}\n\n[OUTPUT FORMAT]\nRespond with ONLY a single JSON object matching this JSON schema — no markdown fences, no commentary, no extra text before or after it:\n${JSON.stringify(responseSchema)}`
      : systemPrompt;
    body = {
      model,
      messages: [
        { role: 'system', content: effectiveSystemPrompt },
        { role: 'user', content: prompt }
      ],
      temperature: 0.1,
    };
    if (responseSchema) {
      // Broadest-compatibility structured-output mode — many self-hosted/
      // aggregator OpenAI-compatible backends don't support the stricter
      // json_schema mode, so this is paired with the prompt instruction
      // above and extractJson()'s tolerant parsing on the caller side.
      body.response_format = { type: 'json_object' };
    }
  }

  const res = await requestHttp(url, method, headers, body);
  if (res.status === 429) {
    throw new Error(`Rate limit exceeded (HTTP 429)`);
  }
  if (res.status < 200 || res.status >= 300) {
    const errMsg = typeof res.data === 'object'
      ? JSON.stringify(res.data)
      : res.data;
    throw new Error(`HTTP ${res.status}: ${errMsg}`);
  }

  if (provider.id === 'anthropic') {
    if (responseSchema) {
      const toolUse = (res.data?.content as any[] | undefined)?.find(
        (block) => block?.type === 'tool_use' && block?.name === STRUCTURED_TOOL_NAME
      );
      if (!toolUse) throw new Error('Invalid response from Anthropic: missing tool_use block');
      return JSON.stringify(toolUse.input);
    }
    const text = res.data?.content?.[0]?.text;
    if (!text) throw new Error('Invalid response from Anthropic: missing content text');
    return text;
  } else {
    const text = res.data?.choices?.[0]?.message?.content;
    if (!text) throw new Error(`Invalid response from ${provider.name}: missing message content`);
    return text;
  }
}

/**
 * Parses a structured AI response into T, tolerating a model that wraps the
 * JSON in a markdown fence or adds stray text around it despite being asked
 * not to (some providers don't strictly honor response_format hints).
 */
export function extractJson<T>(raw: string): T {
  const attempts: string[] = [raw.trim()];

  const fenceMatch = raw.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fenceMatch?.[1]) attempts.push(fenceMatch[1].trim());

  const firstBrace = raw.indexOf('{');
  const lastBrace = raw.lastIndexOf('}');
  if (firstBrace !== -1 && lastBrace > firstBrace) {
    attempts.push(raw.slice(firstBrace, lastBrace + 1));
  }

  for (const attempt of attempts) {
    try {
      return JSON.parse(attempt) as T;
    } catch {
      continue;
    }
  }

  throw new Error(`AI did not return valid JSON: ${raw.slice(0, 200)}`);
}

let nextCallId = 0;
const activeCalls = new Map<string, { providerName: string; model: string }>();
const subscribers = new Set<(calls: { providerName: string; model: string }[]) => void>();

export function subscribeToAICalls(callback: (calls: { providerName: string; model: string }[]) => void): () => void {
  subscribers.add(callback);
  callback(Array.from(activeCalls.values()));
  return () => {
    subscribers.delete(callback);
  };
}

function notifySubscribers() {
  const list = Array.from(activeCalls.values());
  for (const sub of subscribers) {
    sub(list);
  }
}

/**
 * Resolves the provider/key/model fallback chain and invokes it, retrying
 * the next configured provider on failure. Shared by callAI and
 * callAIStructured so the two don't duplicate this logic.
 */
async function resolveAndInvoke(
  prompt: string,
  systemPrompt: string,
  config: AIConfig,
  responseSchema?: JsonSchema
): Promise<string> {
  const providers = await fetchProviders(config);

  const availableProviders: string[] = [];
  for (const p of providers) {
    const key = await getApiKey(p.id);
    if (key) {
      availableProviders.push(p.id);
    }
  }

  if (availableProviders.length === 0) {
    throw new Error('No AI API keys configured. Please configure keys in Settings.');
  }

  let providersToTry = [config.preferredProvider, ...availableProviders.filter(p => p !== config.preferredProvider)];
  providersToTry = providersToTry.filter(p => availableProviders.includes(p));

  if (providersToTry.length === 0) {
    providersToTry = [availableProviders[0]!];
  }

  let lastError = '';

  for (const providerId of providersToTry) {
    const provider = providers.find(p => p.id === providerId);
    if (!provider) continue;

    const key = await getApiKey(providerId);
    if (!key) continue;

    // config.preferredModel is only meaningful for config.preferredProvider
    // — Settings/Onboarding always save them together, and the model is
    // picked from that provider's *live* listModels() result, which is
    // usually not a member of `provider.models` (the static generated
    // list, kept only as a last-resort default). Validating it against
    // that static list here would silently discard a perfectly valid
    // live-picked model and substitute a possibly-stale/retired one
    // instead. For any other (fallback) provider in this loop,
    // preferredModel genuinely doesn't apply, so fall back to its first
    // static model.
    const model = providerId === config.preferredProvider
      ? (config.preferredModel || provider.models[0]?.id || '')
      : (provider.models[0]?.id || '');

    const callId = `call-${nextCallId++}`;
    activeCalls.set(callId, { providerName: provider.name, model });
    notifySubscribers();

    try {
      return await invokeProvider(provider, model, key, prompt, systemPrompt, responseSchema);
    } catch (e: any) {
      console.warn(`Provider ${providerId} failed:`, e);
      lastError = `[${provider.name} / ${model}] ${e.message || String(e)}`;
      continue;
    } finally {
      activeCalls.delete(callId);
      notifySubscribers();
    }
  }

  throw new Error(`AI generation failed. Last error: ${lastError}`);
}

export async function callAI(
  prompt: string,
  systemPrompt: string,
  config: AIConfig
): Promise<string> {
  return resolveAndInvoke(prompt, systemPrompt, config);
}

/**
 * Like callAI, but requests and validates a JSON response matching `schema`
 * instead of returning free text — the explicit contract that replaced
 * sniffing the system prompt for keywords like "duration"/"synopsis".
 */
export async function callAIStructured<T = unknown>(
  prompt: string,
  systemPrompt: string,
  config: AIConfig,
  schema: JsonSchema
): Promise<T> {
  const response = await resolveAndInvoke(prompt, systemPrompt, config, schema);
  return extractJson<T>(response);
}

/** Any provider (from the fetched + custom list) with a stored API key. */
export async function hasConfiguredApiKey(config: AIConfig): Promise<boolean> {
  const providers = await fetchProviders(config);
  for (const p of providers) {
    if (await getApiKey(p.id)) return true;
  }
  return false;
}

/**
 * Fetches the provider's live model list so Settings/Onboarding show
 * current models instead of a potentially stale static one. Never throws —
 * falls back to `provider.models` on any error (missing endpoint, bad key,
 * network failure), since this is a progressive enhancement.
 */
export async function listModels(provider: ProviderConfig, apiKey: string): Promise<ModelConfig[]> {
  try {
    const isAnthropic = provider.id === 'anthropic';
    const url = isAnthropic ? 'https://api.anthropic.com/v1/models' : `${provider.baseUrl}/models`;
    const headers: Record<string, string> = isAnthropic
      ? { 'x-api-key': apiKey, 'anthropic-version': '2023-06-01' }
      : { 'Authorization': `Bearer ${apiKey}` };

    const res = await requestHttp(url, 'GET', headers, null);
    if (res.status < 200 || res.status >= 300) {
      throw new Error(`HTTP ${res.status}`);
    }

    const data = res.data?.data;
    if (!Array.isArray(data) || data.length === 0) {
      throw new Error('Provider returned an empty model list');
    }

    return data.map((m: any) => ({
      id: m.id,
      name: m.display_name || m.id,
    }));
  } catch (e) {
    console.warn(`Failed to list live models for ${provider.id}, using static list:`, e);
    return provider.models;
  }
}

export async function testConnection(providerId: string, apiKey: string, config: AIConfig): Promise<boolean> {
  const providers = await fetchProviders(config);
  const provider = providers.find(p => p.id === providerId);
  if (!provider) throw new Error('Unknown provider');

  const liveModels = await listModels(provider, apiKey);
  const testModel = liveModels[0]?.id;
  if (!testModel) throw new Error('No models found for provider');

  const resText = await invokeProvider(provider, testModel, apiKey, "Hello, reply with one word: OK", "Connection test verification.");
  return resText.trim().length > 0;
}

export function mockActiveCallsList(calls: { providerName: string; model: string }[]) {
  activeCalls.clear();
  calls.forEach((c, idx) => activeCalls.set(`mock-${idx}`, c));
  notifySubscribers();
}

